"use strict";

const NATURAL_COMMAND_ALIASES = Object.freeze({
  help: "/help",
  start: "/start",
  codex: "/codex",
  commands: "/commands",
  command: "/commands",
  c: "/commands",
  status: "/status",
  workers: "/workers",
  worker: "/workers",
  capabilities: "/capabilities",
  capability: "/capabilities",
  use: "/use",
  spawn: "/spawn",
  retire: "/retire",
  queue: "/queue",
  news: "/news",
  newsreport: "/newsreport",
  cancel: "/cancel",
  stop: "/stop",
  clear: "/clear",
  screenshot: "/screenshot",
  ss: "/screenshot",
  sendfile: "/sendfile",
  cmd: "/cmd",
  confirm: "/confirm",
  run: "/run",
  reject: "/reject",
  deny: "/deny",
  cancelcmd: "/cancelcmd",
  new: "/new",
  resume: "/resume",
  compress: "/compress",
  ask: "/ask",
  see: "/see",
  imgclear: "/imgclear",
  model: "/model",
  voice: "/voice",
  tts: "/tts",
  abtest: "/abtest",
  voicetest: "/abtest",
  prune: "/prune",
  wipe: "/wipe",
  restart: "/restart",
  newsstatus: "/newsstatus",
});

const NATURAL_NO_ARG_COMMANDS = new Set([
  "/help",
  "/start",
  "/codex",
  "/commands",
  "/status",
  "/workers",
  "/capabilities",
  "/queue",
  "/cancel",
  "/stop",
  "/clear",
  "/screenshot",
  "/confirm",
  "/run",
  "/reject",
  "/deny",
  "/cancelcmd",
  "/new",
  "/imgclear",
  "/model",
  "/voice",
  "/abtest",
  "/prune",
  "/wipe",
  "/newsstatus",
]);

const NATURAL_PREFIX_REQUIRED_COMMANDS = new Set([
  "/use",
  "/spawn",
  "/retire",
  "/sendfile",
  "/cmd",
  "/resume",
  "/ask",
  "/see",
  "/tts",
]);

const NATURAL_DIRECT_COMMANDS = new Set([
  "/help",
  "/start",
  "/codex",
  "/commands",
  "/status",
  "/workers",
  "/capabilities",
  "/queue",
  "/news",
  "/newsreport",
  "/cancel",
  "/stop",
  "/clear",
  "/screenshot",
  "/confirm",
  "/run",
  "/reject",
  "/deny",
  "/cancelcmd",
  "/new",
  "/compress",
  "/imgclear",
  "/model",
  "/voice",
  "/abtest",
  "/prune",
  "/wipe",
  "/restart",
  "/newsstatus",
]);

module.exports = {
  NATURAL_COMMAND_ALIASES,
  NATURAL_NO_ARG_COMMANDS,
  NATURAL_PREFIX_REQUIRED_COMMANDS,
  NATURAL_DIRECT_COMMANDS,
};
